WITH 
    SOURCE_WC_FORECASTS AS 
    (
    SELECT  CAST (TIMESTAMP(FORECAST_TIMESTAMP) AS DATETIME) AS HORA_PREVISAO
            , CAST (TEAM AS STRING) AS TIME
            , CAST (A.GROUP AS STRING) AS GRUPO
            , CAST (SPI AS NUMERIC) AS SPI 
            , CAST (GLOBAL_O AS NUMERIC) AS GLOBAL_O
            , CAST (GLOBAL_D  AS NUMERIC) AS GLOBA_D
            , CAST (SIM_WINS AS NUMERIC) AS VITORIAS
            , CAST (SIM_TIES AS NUMERIC) AS EMPATES
            , CAST (SIM_LOSSES AS NUMERIC) AS DERROTAS
            , CAST (SIM_GOAL_DIFF AS NUMERIC) AS DIFERENCA_DE_GOAS
            , CAST (GOALS_SCORED AS NUMERIC) AS GOLS_REALIZADOS
            , CAST (GOALS_AGAINST AS NUMERIC) AS GOLS_SOFRIDOS
            , CAST (GROUP_1 AS NUMERIC) AS POSICAO_1
            , CAST (GROUP_2 AS NUMERIC) AS POSICAO_2
            , CAST (GROUP_3 AS NUMERIC) AS POSICAO_3
            , CAST (GROUP_4 AS NUMERIC) AS POSICAO_4
            , CAST (MAKE_ROUND_OF_16 AS NUMERIC) AS CHEGAR_NA_OITAVA_DE_FINAIS
            , CAST (MAKE_QUARTERS AS NUMERIC) AS CHEGAR_NA_QUARTA_DE_FINAIS
            , CAST (MAKE_SEMIS AS NUMERIC) AS CHEGAR_NA_SEMI_FINAL
            , CAST (MAKE_FINAL AS NUMERIC) AS CHEGAR_NA_FINAL
            , CAST (WIN_LEAGUE AS NUMERIC) AS VENCER_LIGA
            --, CAST (TIMESTAMP AS DATE) AS HORA_ATUALIZACAO
    FROM {{source('BASE','WC_FORECASTS')}} A
    )

SELECT * 
FROM SOURCE_WC_FORECASTS